
$(document).ready(function(){
    $("#adicionaUsuario").click(function(){
		$('#modalAdicionaUsuario').modal('show');
    });
	$("#adicionaAgendador").click(function(){
		$('#modalAdicionaAgendador').modal('show');
    });
	$("#adicionaPosicaoCompareceu").click(function(){
		$('#modalAdicionaPosicaoCompareceu').modal('show');
    });
	$("#adicionaSituacaoContratual").click(function(){
		$('#modalAdicionaSituacaoContratual').modal('show');
    });
	$("#adicionaTipoCliente").click(function(){
		$('#modalAdicionaTipoCliente').modal('show');
    });
	$("#adicionaSexo").click(function(){
		$('#modalAdicionaSexo').modal('show');
    });
	$("#adicionaEstadoCivil").click(function(){
		$('#modalAdicionaEstadoCivil').modal('show');
    });
	$("#adicionaTipoLogradouro").click(function(){
		$('#modalAdicionaTipoLogradouro').modal('show');
    });
	$("#adicionaTipoTelefone").click(function(){
		$('#modalAdicionaTipoTelefone').modal('show');
    });
	$("#adicionaForum").click(function(){
		$('#modalAdicionaForum').modal('show');
    });
	$("#adicionaTipoAcaoJudicial").click(function(){
		$('#modalAdicionaTipoAcaoJudicial').modal('show');
    });
	$("#adicionaRitoProcessual").click(function(){
		$('#modalAdicionaRitoProcessual').modal('show');
    });
	$("#adicionaFaseProcessual").click(function(){
		$('#modalAdicionaFaseProcessual').modal('show');
    });
	$("#adicionaStatusProcessual").click(function(){
		$('#modalAdicionaStatusProcessual').modal('show');
    });
	$("#adicionaDecisao").click(function(){
		$('#modalAdicionaDecisao').modal('show');
    });
	$("#adicionaPosicaoCliente").click(function(){
		$('#modalAdicionaPosicaoCliente').modal('show');
    });
	$("#adicionaPosicaoContrario").click(function(){
		$('#modalAdicionaPosicaoContrario').modal('show');
    });
	$("#adicionaPosicaoAdvogado").click(function(){
		$('#modalAdicionaPosicaoAdvogado').modal('show');
    });
	$("#adicionaTipoAcompanhamento").click(function(){
		$('#modalAdicionaTipoAcompanhamento').modal('show');
    });
	$("#adicionaAdvogadoPatrono").click(function(){
		$('#modalAdicionaAdvogadoPatrono').modal('show');
    });
	$("#adicionaTipoAudiencia").click(function(){
		$('#modalAdicionaTipoAudiencia').modal('show');
    });
	$("#adicionaAdvogadoDesignado").click(function(){
		$('#modalAdicionaAdvogadoDesignado').modal('show');
    });
	$("#mostraUsuario").click(function(){
		$('#modalMostraUsuario').modal('show');
    });
	$("#mostraAgente").click(function(){
		$('#modalMostraAgente').modal('show');
    });
	$("#mostraPosicaoCompareceu").click(function(){
		$('#modalMostraPosicaoCompareceu').modal('show');
    });
	$("#mostraSituacaoContratual").click(function(){
		$('#modalMostraSituacaoContratual').modal('show');
    });
	$("#mostraTipoCliente").click(function(){
		$('#modalMostraTipoCliente').modal('show');
    });
	$("#mostraSexo").click(function(){
		$('#modalMostraSexo').modal('show');
    });
	$("#mostraEstadoCivil").click(function(){
		$('#modalMostraEstadoCivil').modal('show');
    });
	$("#mostraTipoLogradouro").click(function(){
		$('#modalMostraTipoLogradouro').modal('show');
    });
	$("#mostraTipoTelefone").click(function(){
		$('#modalMostraTipoTelefone').modal('show');
    });
	$("#mostraForum").click(function(){
		$('#modalMostraForum').modal('show');
    });
	$("#mostraTipoAcaoJudicial").click(function(){
		$('#modalMostraTipoAcaoJudicial').modal('show');
    });
	$("#mostraRitoProcessual").click(function(){
		$('#modalMostraRitoProcessual').modal('show');
    });
	$("#mostraFaseProcessual").click(function(){
		$('#modalMostraFaseProcessual').modal('show');
    });
	$("#mostraStatusProcessual").click(function(){
		$('#modalMostraStatusProcessual').modal('show');
    });
	$("#mostraDecisao").click(function(){
		$('#modalMostraDecisao').modal('show');
    });
	$("#mostraPosicaoCliente").click(function(){
		$('#modalMostraPosicaoCliente').modal('show');
    });
	$("#mostraPosicaoContrario").click(function(){
		$('#modalMostraPosicaoContrario').modal('show');
    });
	$("#mostraPosicaoAdvogado").click(function(){
		$('#modalMostraPosicaoAdvogado').modal('show');
    });
	$("#mostraTipoAcompanhamento").click(function(){
		$('#modalMostraTipoAcompanhamento').modal('show');
    });
	$("#mostraAdvogadoPatrono").click(function(){
		$('#modalMostraAdvogadoPatrono').modal('show');
    });
	$("#mostraTipoAudiencia").click(function(){
		$('#modalMostraTipoAudiencia').modal('show');
    });
	$("#mostraAdvogadoDesignado").click(function(){
		$('#modalMostraAdvogadoDesignado').modal('show');
    });
	
	
	$(function() {
        $('#corAgendador').colorpicker({
			format: "hex"
		});
    });
	$(function() {
        $('#corPosicaoCompareceu').colorpicker({
			format: "hex"
		});
    });
	$(function() {
        $('#corSituacaoContratual').colorpicker({
			format: "hex"
		});
    });

});

